import { LandingNav } from "@/components/landing/LandingNav";
import { Footer } from "@/components/landing/Footer";

export default function TermsOfService() {
    return (
        <div className="min-h-screen bg-white">
            <LandingNav />
            <div className="pt-24 pb-16 max-w-3xl mx-auto px-4 prose prose-slate">
                <h1>Terms of Service</h1>
                <p className="text-gray-600"><em>Last updated: {new Date().toLocaleDateString()}</em></p>

                <h2>1. Acceptance of Terms</h2>
                <p>By using Sokrate AI, you agree to these terms of service. If you do not agree, please do not use our service.</p>

                <h2>2. Description of Service</h2>
                <p>Sokrate AI provides AI-powered educational tools including problem solving, document synthesis, and quiz generation for students in scientific disciplines.</p>

                <h2>3. User Responsibilities</h2>
                <p>You are responsible for maintaining the confidentiality of your account and for all activities under your account. You agree not to use the service for any unlawful purpose.</p>

                <h2>4. Intellectual Property</h2>
                <p>All content generated by the AI remains informational in nature. Users retain ownership of their uploaded documents.</p>

                <h2>5. Limitation of Liability</h2>
                <p>Sokrate AI provides solutions for educational purposes. We do not guarantee the accuracy of all solutions and recommend independent verification for critical academic work.</p>

                <h2>6. Contact</h2>
                <p>For questions about these terms, please contact us at support@sokrate-ai.com.</p>
            </div>
            <Footer />
        </div>
    );
}