import { useEffect } from "react";
import { LandingNav } from "@/components/landing/LandingNav";
import { Footer } from "@/components/landing/Footer";

export default function TermsOfService() {
    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    return (
        <div className="landing-page min-h-screen bg-[#0B0F14]">
            <LandingNav />
            <div className="pt-24 pb-16 max-w-3xl mx-auto px-4 text-white/90">
                <h1 className="font-heading text-3xl font-bold text-white tracking-tight mb-2">Terms of Service</h1>
                <p className="text-white/60 text-sm mb-8"><em>Last updated: {new Date().toLocaleDateString()}</em></p>

                <h2 className="font-heading text-xl font-semibold text-white mt-8 mb-2">1. Acceptance of Terms</h2>
                <p className="text-white/80 leading-relaxed mb-4">By using Sokrate AI, you agree to these terms of service. If you do not agree, please do not use our service.</p>

                <h2 className="font-heading text-xl font-semibold text-white mt-8 mb-2">2. Description of Service</h2>
                <p className="text-white/80 leading-relaxed mb-4">Sokrate AI provides AI-powered educational tools including notes from documents and links, flashcards, and quiz generation for students.</p>

                <h2 className="font-heading text-xl font-semibold text-white mt-8 mb-2">3. User Responsibilities</h2>
                <p className="text-white/80 leading-relaxed mb-4">You are responsible for maintaining the confidentiality of your account and for all activities under your account. You agree not to use the service for any unlawful purpose.</p>

                <h2 className="font-heading text-xl font-semibold text-white mt-8 mb-2">4. Intellectual Property</h2>
                <p className="text-white/80 leading-relaxed mb-4">All content generated by the AI remains informational in nature. Users retain ownership of their uploaded documents.</p>

                <h2 className="font-heading text-xl font-semibold text-white mt-8 mb-2">5. Limitation of Liability</h2>
                <p className="text-white/80 leading-relaxed mb-4">Sokrate AI is for educational purposes. We do not guarantee the accuracy of all output and recommend independent verification for critical academic work.</p>

                <h2 className="font-heading text-xl font-semibold text-white mt-8 mb-2">6. Contact</h2>
                <p className="text-white/80 leading-relaxed">For questions about these terms, please contact us at support@sokrate-ai.com.</p>
            </div>
            <Footer />
        </div>
    );
}